'use client';

import React, { useMemo } from 'react';
import { Handle, Position } from '@xyflow/react';
import {
  Key,
  Link2,
  Calculator,
  CheckCircle,
  Sparkles,
  Circle,
  Layers,
  MoreHorizontal,
  Globe,
  Brain,
  ALargeSmall,
  Braces,
  GitBranch,
  Search,
} from 'lucide-react';
import { cn } from '@/lib/utils';
import { Column } from '@/lib/types';
import {
  parseColumnType,
  sanitizeTypeString,
  getVisibleBadges,
  BadgeInfo,
} from '@/lib/schema-display-utils';
import {
  Tooltip,
  TooltipContent,
  TooltipProvider,
  TooltipTrigger,
} from '@/components/ui/tooltip';

interface SmartColumnRowProps {
  column: Column;
  tableName: string;
  index: number;
  selected?: boolean;
}

/**
 * Icon mapping for badge types with accessibility support
 */
const BadgeIcon: React.FC<{ badge: BadgeInfo; className?: string }> = ({
  badge,
  className,
}) => {
  const iconClass = cn('w-3 h-3', className);
  const ariaLabel = badge.tooltip || badge.type;

  switch (badge.icon) {
    case 'Key':
      return (
        <Key
          className={cn(iconClass, 'text-yellow-500')}
          aria-label={ariaLabel}
          role="img"
        />
      );
    case 'Link2':
      return (
        <Link2
          className={cn(iconClass, 'text-emerald-500')}
          aria-label={ariaLabel}
          role="img"
        />
      );
    case 'Calculator':
      return (
        <Calculator
          className={cn(iconClass, 'text-purple-500')}
          aria-label={ariaLabel}
          role="img"
        />
      );
    case 'CheckCircle':
      return (
        <CheckCircle
          className={cn(iconClass, 'text-orange-500')}
          aria-label={ariaLabel}
          role="img"
        />
      );
    case 'Sparkles':
      return (
        <Sparkles
          className={cn(iconClass, 'text-blue-500')}
          aria-label={ariaLabel}
          role="img"
        />
      );
    case 'Layers':
      return (
        <Layers
          className={cn(iconClass, 'text-gray-500')}
          aria-label={ariaLabel}
          role="img"
        />
      );
    // Extension type icons
    case 'Globe':
      return (
        <Globe
          className={cn(iconClass, 'text-teal-500')}
          aria-label={ariaLabel}
          role="img"
        />
      );
    case 'Brain':
      return (
        <Brain
          className={cn(iconClass, 'text-pink-500')}
          aria-label={ariaLabel}
          role="img"
        />
      );
    case 'CaseSensitive':
      return (
        <ALargeSmall
          className={cn(iconClass, 'text-indigo-500')}
          aria-label={ariaLabel}
          role="img"
        />
      );
    case 'Braces':
      return (
        <Braces
          className={cn(iconClass, 'text-amber-500')}
          aria-label={ariaLabel}
          role="img"
        />
      );
    case 'GitBranch':
      return (
        <GitBranch
          className={cn(iconClass, 'text-lime-500')}
          aria-label={ariaLabel}
          role="img"
        />
      );
    case 'Search':
      return (
        <Search
          className={cn(iconClass, 'text-cyan-500')}
          aria-label={ariaLabel}
          role="img"
        />
      );
    default:
      return null;
  }
};

/**
 * SmartColumnRow - A performance-optimized column row component that:
 * 1. Uses memoization to avoid regex parsing on every render
 * 2. Displays abbreviated type with badges using priority logic
 * 3. Shows full details on hover via Portal-based tooltip
 * 4. Includes accessibility features (aria-labels, keyboard navigation)
 */
export const SmartColumnRow: React.FC<SmartColumnRowProps> = React.memo(
  ({ column, tableName, index, selected }) => {
    const handleId = `${tableName}_${column.title}_${index}`;

    // MEMOIZED: Only re-parse if column.format changes
    const { baseType, modifiers } = useMemo(
      () => parseColumnType(sanitizeTypeString(column.format)),
      [column.format],
    );

    // MEMOIZED: Badge priority calculation
    const badges = useMemo(() => {
      // Merge stored modifiers with parsed modifiers
      const mergedColumn = {
        ...column,
        modifiers: { ...column.modifiers, ...modifiers },
      };
      return getVisibleBadges(mergedColumn);
    }, [column, modifiers]);

    const isPK = column.pk;
    const isFK = column.fk || modifiers.references;

    // Build tooltip content for screen readers and hover
    const tooltipContent = useMemo(() => {
      const parts: string[] = [`Type: ${column.format}`];

      if (modifiers.identity) {
        parts.push(
          `Identity: ${modifiers.identity === 'always' ? 'GENERATED ALWAYS' : 'GENERATED BY DEFAULT'}`,
        );
      }

      if (modifiers.generated) {
        parts.push(`Computed: ${modifiers.generated.expression}`);
      }

      if (modifiers.check) {
        parts.push(`Check: ${modifiers.check.expression}`);
      }

      if (column.fk) {
        parts.push(`References: ${column.fk}`);
      }

      if (column.default !== undefined) {
        parts.push(`Default: ${column.default}`);
      }

      if (column.required) {
        parts.push('Required: Yes');
      }

      if (column.unique) {
        parts.push('Unique: Yes');
      }

      return parts.join('\n');
    }, [column, modifiers]);

    // Build aria-label for the entire row
    const rowAriaLabel = useMemo(() => {
      const parts = [column.title, baseType];
      if (isPK) parts.push('Primary Key');
      if (isFK) parts.push('Foreign Key');
      if (column.required) parts.push('Required');
      if (column.unique) parts.push('Unique');
      return parts.join(', ');
    }, [column, baseType, isPK, isFK]);

    return (
      <div
        className={cn(
          'relative group py-2 px-3 flex items-center gap-2 border-b border-border/50 last:border-b-0',
          'hover:bg-muted/40 transition-colors',
          'border-l-[3px] border-transparent',
          isPK && 'border-l-yellow-500/50',
          'focus-within:bg-muted/60',
        )}
        role="row"
        aria-label={rowAriaLabel}
        tabIndex={0}
      >
        {/* Left Handle - Target (for incoming connections) */}
        <Handle
          type="target"
          position={Position.Left}
          id={handleId}
          className={cn(
            '!w-3 !h-3 !bg-blue-500 !border-2 !border-background !-left-[9px] !transition-opacity',
            selected ? '!opacity-100' : '!opacity-0',
          )}
          style={{ top: '50%', transform: 'translateY(-50%)' }}
          aria-hidden="true"
        />

        {/* Right Handle - Source (for outgoing connections) */}
        <Handle
          type="source"
          position={Position.Right}
          id={handleId}
          className={cn(
            '!w-3 !h-3 !border-2 !border-background !-right-[7px] !transition-opacity',
            isFK ? '!bg-emerald-500' : '!bg-blue-500',
            selected ? '!opacity-100' : '!opacity-0',
          )}
          style={{ top: '50%', transform: 'translateY(-50%)' }}
          aria-hidden="true"
        />

        {/* Primary badge icon */}
        <div className="shrink-0 w-4 flex justify-center" aria-hidden="true">
          {badges[0] ? (
            <BadgeIcon badge={badges[0]} />
          ) : (
            <Circle className="h-2 w-2 text-muted-foreground/30" />
          )}
        </div>

        {/* Column Name */}
        <span
          className="flex-1 text-sm font-medium truncate font-mono"
          title={column.title}
        >
          {column.title}
        </span>

        {/* Abbreviated Type (max-width with truncation) */}
        <span
          className="text-xs text-muted-foreground font-mono shrink-0 max-w-[100px] truncate"
          title={column.format}
          aria-label={`Type: ${baseType}${modifiers.isArray ? ' array' : ''}`}
        >
          {baseType}
          {modifiers.isArray ? '[]' : ''}
        </span>

        {/* Additional badges (after primary) */}
        <div
          className="flex items-center gap-0.5"
          role="group"
          aria-label="Column modifiers"
        >
          {badges.slice(1, 3).map((badge) => (
            <React.Fragment key={badge.type}>
              {badge.label ? (
                <span
                  className={cn(
                    'text-[9px] font-bold px-1 rounded',
                    badge.color === 'blue' &&
                      'bg-blue-100 text-blue-600 dark:bg-blue-900/30 dark:text-blue-400',
                    badge.color === 'purple' &&
                      'bg-purple-100 text-purple-600 dark:bg-purple-900/30 dark:text-purple-400',
                    badge.color === 'orange' &&
                      'bg-orange-100 text-orange-600 dark:bg-orange-900/30 dark:text-orange-400',
                    badge.color === 'red' && 'text-red-500',
                    badge.color === 'gray' &&
                      'bg-gray-100 text-gray-600 dark:bg-gray-800 dark:text-gray-400',
                    badge.color === 'teal' &&
                      'bg-teal-100 text-teal-600 dark:bg-teal-900/30 dark:text-teal-400',
                  )}
                  title={badge.tooltip}
                  aria-label={badge.tooltip || badge.type}
                  role="status"
                >
                  {badge.label}
                </span>
              ) : (
                <span title={badge.tooltip}>
                  <BadgeIcon badge={badge} className="w-2.5 h-2.5" />
                </span>
              )}
            </React.Fragment>
          ))}

          {/* Overflow indicator + full tooltip */}
          <TooltipProvider>
            <Tooltip>
              <TooltipTrigger asChild>
                <button
                  className="opacity-0 group-hover:opacity-100 focus:opacity-100 transition-opacity cursor-help ml-1 p-0.5 rounded hover:bg-muted"
                  aria-label="View column details"
                  type="button"
                >
                  <MoreHorizontal className="w-3 h-3 text-muted-foreground" />
                </button>
              </TooltipTrigger>
              <TooltipContent
                side="right"
                className="max-w-[300px] whitespace-pre-wrap font-mono text-xs"
              >
                {tooltipContent}
              </TooltipContent>
            </Tooltip>
          </TooltipProvider>
        </div>
      </div>
    );
  },
);

SmartColumnRow.displayName = 'SmartColumnRow';
